### ISSUE TITLE
Installing/running instructions

### ISSUE THREAD

**Issue by nodiscc** [elima/FileTea#3]
Hi, the README is unfortunately empty and I'd like to have some guidance on how to setup and run filetea on a Linux box.

**Comment by fietronic** [comment]
Seconded. It seems like it might be a simple make make install but I'm not sure. Imma try.

**Comment by ghost** [comment]
@fietronic Could you successful install filetea? I am also interested in using filetea.

**Comment by emanuelstanciu** [comment]
https://www.howtoinstall.co/en/ubuntu/trusty/filetea

do a `apt-cache search filetea` in Debian/Ubuntu and you should find the package

**Comment by nodiscc** [comment]
Filetea is not maintained anymore (though the Debian package is available, yes), so I'd recommend installing something under development instead (this is what I've done). You can find reasonable alternatives here: https://github.com/Kickball/awesome-selfhosted#peer-to-peer-filesharing.

I'm going to close this since maintainers are missing :/
